version: '3.9'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    hostname: app
    restart: always
    tty: true
    volumes:
      - ./:/var/www/html/
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    expose:
      - 80
      - 443
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8-debian
    container_name: mysql
    restart: always
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_ROOT_PASSWORD=iTYUI7*76oKVHJruyi3ol
      - MYSQL_DATABASE=app
    networks:
      - app-network
    volumes:
      - ./mysql:/var/lib/mysql
networks:
  app-network:
    driver: bridge
